version: '3'
services:
  java:
    image: openjdk:11
    working_dir: /app
    volumes:
      - ./java:/app
      - ./data:/data
    command: ["sh", "-c", "tail -f /dev/null"]
  python:
    build:
      context: ./python
    volumes:
      - ./python:/app
      - ./data:/data
    command: ["sh", "-c", "tail -f /dev/null"]